Task1:

1. Create a list of 5 fruits and print them one by one.

In [2]:
import numpy as np
fruits=["apple","grapes","orange","pineapple","mango"]
for fruit in fruits:
    print(fruit)

apple
grapes
orange
pineapple
mango


2. Create an array of integers from 1 to 10 and calculate their sum.

In [3]:
arr = np.arange(1,11)
sum = arr.sum()
print("array",arr)
print("sum",sum)

array [ 1  2  3  4  5  6  7  8  9 10]
sum 55


3. Store student names and scores together and print

In [15]:
students = {
 "sanjay":   85,
 "ram":      97,
 "vishnu":   89
}    
for name, score in students.items():
     print(name,":",score)

sanjay : 85
ram : 97
vishnu : 89


4. Store the temperature for 10 days and calculate average

In [1]:
temperature = (32,23,15,24,13,16,17,12,13,12)
average = sum(temperature) / len(temperature)

print("temperature:", temperature)
print("average temperature for 10 days:", average)

temperature: (32, 23, 15, 24, 13, 16, 17, 12, 13, 12)
average temperature for 10 days: 17.7


5. Print an array from 10 to 50 with step 5

In [3]:
import numpy as np 
arr = np.arange(10,51, 5)
print(arr)

[10 15 20 25 30 35 40 45 50]


6. 

In [9]:
a=np.array([[3,2],[4,2]])
b=np.array([[1,3],[1,2]])
print(np.dot(a,b))

[[ 5 13]
 [ 6 16]]


Task2:

1. Create a 1D NumPy array named arr with values [5, 10, 15, 20, 25, 30]. Print the following for the array:
Shape
Number of dimensions (ndim)
Data type (dtype)
Total number of elements (size)

In [12]:
array=np.array([5,10,15,20,25,30])
print(array.shape)
print(array.ndim)
print(array.size)
print(array.dtype)

(6,)
1
6
int64


2. Create a 3x3 array filled with zeros and another 2x4 array filled with ones.

In [14]:
zeros_array=np.zeros((3,3))
ones_array=np.ones((2,4))
print(zeros_array)
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


3. Given the 2D array:
scores = np.array([[85, 78, 92],
                   [90, 88, 76],
                   [72, 95, 89],
                   [88, 82, 91]])
                   
        a. Reverse the entire array using two different methods.
        b. Extract the second row (index 1).
        c. Reverse all rows (flip upside down).

In [10]:
import numpy as np
scores = ([
        [90,88,76],
        [72,95,89],
        [88,82,91]
 ])
print("original array")
print(scores)
method_a=scores[::-1]
print("reverse the entire array method(a):")
print(method_a)
method_b=np.flip(scores)
print("reverse the entire array method(b):")
print(method_b)
second_row=[1]
print("second row:")
print(second_row)
reverse_all_rows=np.flipud(scores)
print("reverse all rows")
print(reverse_all_rows)

original array
[[90, 88, 76], [72, 95, 89], [88, 82, 91]]
reverse the entire array method(a):
[[88, 82, 91], [72, 95, 89], [90, 88, 76]]
reverse the entire array method(b):
[[91 82 88]
 [89 95 72]
 [76 88 90]]
second row:
[1]
reverse all rows
[[88 82 91]
 [72 95 89]
 [90 88 76]]


 4. Create a 1D array with numbers from 1 to 12. Then reshape it into:
   a. 3x4 matrix
   b. 6x2 matrix

In [5]:
import numpy as np
array = np.arange(1,13)
print("original 1D array")
print(array)
matrix1=array.reshape(3,4)
print("matrix 3x4")
print(matrix1)
matrix2=array.reshape(6,2)
print("matrix 6x4")
print(matrix2)

original 1D array
[ 1  2  3  4  5  6  7  8  9 10 11 12]
matrix 3x4
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
matrix 6x4
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


 5. Flatten the 3x4 matrix back to 1D using flatten().

In [6]:
flat = matrix1.flatten()
print("flattened array")
print(flat)

flattened array
[ 1  2  3  4  5  6  7  8  9 10 11 12]


 6. vec = np.array([10, 20, 30, 40]). Convert this vector into a column vector and row vector

In [9]:
vec = np.array([10,20,30,40])
row_vector = vec.reshape(1,4)
print("row vector")
print(row_vector)
column_vector = vec.reshape(4,1)
print("column vector:")
print(column_vector)

row vector
[[10 20 30 40]]
column vector:
[[10]
 [20]
 [30]
 [40]]


 7. a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40]) 
  
  a. Add a & b element wise
  b. Multiply every element of a by 5.

In [10]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
addition =a+b
print("Addition:", addition)
multiplication=a*5
print("multiplication;",multiplication)

Addition: [11 22 33 44]
multiplication; [ 5 10 15 20]


 8. Sort the following array in ascending and descending order:
marks = np.array([67, 92, 45, 88, 75, 91, 55, 89])

In [13]:
marks = ([67,92,45,88,75,91,55,89])
ascending = np.sort(marks)
descending= np.sort(marks)[::-1]
print("ascending order:",ascending)
print("descending order:",descending)

ascending order: [45 55 67 75 88 89 91 92]
descending order: [92 91 89 88 75 67 55 45]


 9. Multiply a 3×3 matrix by a 1D array [1, 2, 3].

In [14]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr = np.array([1,2,3])
result = matrix*arr
print("result",result)

result [[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


10. Create a 4x3 matrix and replace the last column with zero.

In [10]:
import numpy as np
matrix = np.array([ 
                    [1,2,3],
                    [4,5,6],
                    [7,8,9],
                  [10,11,12]
 ])
print("original matrix")
print(matrix)
matrix[:, -1]=0
print("updated_matrix",matrix)

original matrix
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
updated_matrix [[ 1  2  0]
 [ 4  5  0]
 [ 7  8  0]
 [10 11  0]]


11. Sort an array and find its index based on original

In [11]:
array = ([2,3,4,5])
print(array)
sort = np.sort(array)
indices = np.argsort(array)
print(sort)
print(indices)

[2, 3, 4, 5]
[2 3 4 5]
[0 1 2 3]
